# Cosa config file

domain: www.yourdomain.com

# Amount of time between crawls on the same page
# 86400 seconds by default (1 day)
shelf_life: 86400

# Ex) db_path: sqlite:///Users/username/Documents/crawler/data/database.sqlite
db_path: sqlite:///absolute/path/to/database.sqlite

# Exceptions - regex expression for paths that Cosa should ignore
# Ex) - .+\/directory\/.+ will ignore every url that contains /directory/
exceptions:

